name: 'olist_pipeline'
version: '1.0.0'
config-version: 2
 
profile: 'olist_pipeline'
 
on-run-start:
  - "SET spark.hadoop.fs.hdfs.impl.disable.cache=true"
 
model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
 
models:
  olist_pipeline:
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
 